"""baseline

Revision ID: 437c961ee28c
Revises: 
Create Date: 2026-04-14 16:13:26.886593
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '437c961ee28c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('actor_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('causation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('inverse_payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'seq')
    )
    op.create_table('competitions',
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('competition_type', sa.Integer(), nullable=False),
    sa.Column('competition_tag', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('competition_id')
    )
    op.create_table('idempotency_keys',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('request_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('key'),
    sa.UniqueConstraint('user_id', 'key')
    )
    op.create_table('players',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('wsop_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profile_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('player_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('synced_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('player_id'),
    sa.UniqueConstraint('wsop_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('series_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('begin_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('time_zone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_displayed', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('synced_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.competition_id'], ),
    sa.PrimaryKeyConstraint('series_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_series_id', sa.Integer(), nullable=True),
    sa.Column('last_event_id', sa.Integer(), nullable=True),
    sa.Column('last_flight_id', sa.Integer(), nullable=True),
    sa.Column('last_table_id', sa.Integer(), nullable=True),
    sa.Column('last_screen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('token_expires_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('event_no', sa.Integer(), nullable=False),
    sa.Column('event_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('buy_in', sa.Integer(), nullable=True),
    sa.Column('display_buy_in', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('game_type', sa.Integer(), nullable=False),
    sa.Column('bet_structure', sa.Integer(), nullable=False),
    sa.Column('event_game_type', sa.Integer(), nullable=False),
    sa.Column('game_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('allowed_games', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rotation_order', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rotation_trigger', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('blind_structure_id', sa.Integer(), nullable=True),
    sa.Column('starting_chip', sa.Integer(), nullable=True),
    sa.Column('table_size', sa.Integer(), nullable=False),
    sa.Column('total_entries', sa.Integer(), nullable=False),
    sa.Column('players_left', sa.Integer(), nullable=False),
    sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('synced_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.series_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('event_flights',
    sa.Column('event_flight_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_tbd', sa.Boolean(), nullable=False),
    sa.Column('entries', sa.Integer(), nullable=False),
    sa.Column('players_left', sa.Integer(), nullable=False),
    sa.Column('table_count', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('play_level', sa.Integer(), nullable=False),
    sa.Column('remain_time', sa.Integer(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('synced_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('event_flight_id')
    )
    op.create_table('tables',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('event_flight_id', sa.Integer(), nullable=False),
    sa.Column('table_no', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.Integer(), nullable=False),
    sa.Column('small_blind', sa.Integer(), nullable=True),
    sa.Column('big_blind', sa.Integer(), nullable=True),
    sa.Column('ante_type', sa.Integer(), nullable=False),
    sa.Column('ante_amount', sa.Integer(), nullable=False),
    sa.Column('rfid_reader_id', sa.Integer(), nullable=True),
    sa.Column('deck_registered', sa.Boolean(), nullable=False),
    sa.Column('output_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_game', sa.Integer(), nullable=True),
    sa.Column('delay_seconds', sa.Integer(), nullable=False),
    sa.Column('ring', sa.Integer(), nullable=True),
    sa.Column('is_breaking_table', sa.Boolean(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['event_flight_id'], ['event_flights.event_flight_id'], ),
    sa.PrimaryKeyConstraint('table_id'),
    sa.UniqueConstraint('event_flight_id', 'name')
    )
    op.create_table('table_seats',
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('seat_no', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('wsop_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('player_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('chip_count', sa.Integer(), nullable=False),
    sa.Column('profile_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_move_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint('seat_no >= 0 AND seat_no <= 9'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.table_id'], ),
    sa.PrimaryKeyConstraint('seat_id'),
    sa.UniqueConstraint('table_id', 'seat_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_seats')
    op.drop_table('tables')
    op.drop_table('event_flights')
    op.drop_table('events')
    op.drop_table('user_sessions')
    op.drop_table('series')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('players')
    op.drop_table('idempotency_keys')
    op.drop_table('competitions')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
