import type { Competition, Series, Event, EventFlight, Table, TableSeat, Player, User, BlindStructure } from '../types/models'

const NOW = '2026-04-09T12:00:00'

export const mockCompetitions: Competition[] = [
  {
    competition_id: 1,
    name: 'WSOP',
    competition_type: 1,
    competition_tag: 1,
    created_at: NOW,
    updated_at: NOW,
  },
]

export const mockSeries: Series[] = [
  {
    series_id: 1,
    competition_id: 1,
    series_name: 'WSOP Europe 2026',
    year: 2026,
    begin_at: '2026-04-01T12:00:00',
    end_at: '2026-04-20T12:00:00',
    image_url: null,
    time_zone: 'Europe/Paris',
    currency: 'EUR',
    country_code: 'FR',
    is_completed: false,
    is_displayed: true,
    is_demo: false,
    source: 'manual',
    synced_at: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    series_id: 2,
    competition_id: 1,
    series_name: '58th Annual WSOP',
    year: 2026,
    begin_at: '2026-05-28T12:00:00',
    end_at: '2026-07-17T12:00:00',
    image_url: null,
    time_zone: 'America/Los_Angeles',
    currency: 'USD',
    country_code: 'US',
    is_completed: false,
    is_displayed: true,
    is_demo: false,
    source: 'manual',
    synced_at: null,
    created_at: NOW,
    updated_at: NOW,
  },
]

export const mockEvents: Event[] = [
  {
    event_id: 1,
    series_id: 1,
    event_no: 1,
    event_name: '#1 €1,100 Mystery Bounty NLH',
    buy_in: 1100,
    display_buy_in: '€1,100',
    game_type: 0,
    bet_structure: 0,
    event_game_type: 0,
    game_mode: 'tournament',
    allowed_games: null,
    rotation_order: null,
    rotation_trigger: null,
    blind_structure_id: null,
    starting_chip: 30000,
    table_size: 9,
    total_entries: 542,
    players_left: 87,
    start_time: '2026-04-05T14:00:00',
    status: 'running',
    source: 'manual',
    synced_at: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    event_id: 2,
    series_id: 1,
    event_no: 2,
    event_name: '#2 €600 PLO/PLO8/Big O',
    buy_in: 600,
    display_buy_in: '€600',
    game_type: 21,
    bet_structure: 1,
    event_game_type: 21,
    game_mode: 'mix',
    allowed_games: '2,3,11',
    rotation_order: '2,3,11',
    rotation_trigger: 'level',
    blind_structure_id: null,
    starting_chip: 20000,
    table_size: 9,
    total_entries: 0,
    players_left: 0,
    start_time: '2026-04-10T14:00:00',
    status: 'registering',
    source: 'manual',
    synced_at: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    event_id: 3,
    series_id: 1,
    event_no: 3,
    event_name: '#3 €550 Deepstack NLH',
    buy_in: 550,
    display_buy_in: '€550',
    game_type: 0,
    bet_structure: 0,
    event_game_type: 0,
    game_mode: 'tournament',
    allowed_games: null,
    rotation_order: null,
    rotation_trigger: null,
    blind_structure_id: null,
    starting_chip: 40000,
    table_size: 9,
    total_entries: 388,
    players_left: 0,
    start_time: '2026-04-03T14:00:00',
    status: 'completed',
    source: 'manual',
    synced_at: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    event_id: 5,
    series_id: 1,
    event_no: 5,
    event_name: '#5 €5,300 Main Event NLH',
    buy_in: 5300,
    display_buy_in: '€5,300',
    game_type: 0,
    bet_structure: 0,
    event_game_type: 0,
    game_mode: 'tournament',
    allowed_games: null,
    rotation_order: null,
    rotation_trigger: null,
    blind_structure_id: null,
    starting_chip: 50000,
    table_size: 9,
    total_entries: 1486,
    players_left: 918,
    start_time: '2026-04-07T12:00:00',
    status: 'running',
    source: 'manual',
    synced_at: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    event_id: 6,
    series_id: 1,
    event_no: 6,
    event_name: '#6 €600 Turbo NLH',
    buy_in: 600,
    display_buy_in: '€600',
    game_type: 0,
    bet_structure: 0,
    event_game_type: 0,
    game_mode: 'tournament',
    allowed_games: null,
    rotation_order: null,
    rotation_trigger: null,
    blind_structure_id: null,
    starting_chip: 15000,
    table_size: 9,
    total_entries: 0,
    players_left: 0,
    start_time: '2026-04-12T18:00:00',
    status: 'announced',
    source: 'manual',
    synced_at: null,
    created_at: NOW,
    updated_at: NOW,
  },
]

export const mockFlights: EventFlight[] = [
  {
    event_flight_id: 1,
    event_id: 5,
    display_name: 'Day 1A',
    start_time: '2026-04-07T12:00:00',
    is_tbd: false,
    entries: 336,
    players_left: 0,
    table_count: 136,
    status: 'completed',
    play_level: 12,
    remain_time: null,
    source: 'manual',
    synced_at: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    event_flight_id: 2,
    event_id: 5,
    display_name: 'Day 1B',
    start_time: '2026-04-07T17:00:00',
    is_tbd: false,
    entries: 269,
    players_left: 0,
    table_count: 140,
    status: 'completed',
    play_level: 12,
    remain_time: null,
    source: 'manual',
    synced_at: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    event_flight_id: 3,
    event_id: 5,
    display_name: 'Day 1C',
    start_time: '2026-04-08T12:00:00',
    is_tbd: false,
    entries: 299,
    players_left: 0,
    table_count: 154,
    status: 'completed',
    play_level: 12,
    remain_time: null,
    source: 'manual',
    synced_at: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    event_flight_id: 4,
    event_id: 5,
    display_name: 'Day 2',
    start_time: '2026-04-09T12:00:00',
    is_tbd: false,
    entries: 918,
    players_left: 918,
    table_count: 124,
    status: 'running',
    play_level: 3,
    remain_time: 3240,
    source: 'manual',
    synced_at: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    event_flight_id: 5,
    event_id: 5,
    display_name: 'Day 3',
    start_time: '2026-04-10T12:00:00',
    is_tbd: false,
    entries: 0,
    players_left: 0,
    table_count: 0,
    status: 'announced',
    play_level: 0,
    remain_time: null,
    source: 'manual',
    synced_at: null,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    event_flight_id: 6,
    event_id: 5,
    display_name: 'Day 4',
    start_time: '2026-04-11T12:00:00',
    is_tbd: false,
    entries: 0,
    players_left: 0,
    table_count: 0,
    status: 'announced',
    play_level: 0,
    remain_time: null,
    source: 'manual',
    synced_at: null,
    created_at: NOW,
    updated_at: NOW,
  },
]

export const mockTables: Table[] = [
  {
    table_id: 1,
    event_flight_id: 4,
    table_no: 71,
    name: 'Day2-#071',
    type: 'feature',
    status: 'live',
    max_players: 9,
    game_type: 0,
    small_blind: 1200,
    big_blind: 2400,
    ante_type: 1,
    ante_amount: 2400,
    rfid_reader_id: 1,
    deck_registered: true,
    output_type: 'NDI',
    current_game: 47,
    delay_seconds: 30,
    ring: null,
    is_breaking_table: false,
    source: 'manual',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    table_id: 2,
    event_flight_id: 4,
    table_no: 69,
    name: 'Day2-#069',
    type: 'general',
    status: 'live',
    max_players: 9,
    game_type: 0,
    small_blind: 1200,
    big_blind: 2400,
    ante_type: 1,
    ante_amount: 2400,
    rfid_reader_id: null,
    deck_registered: false,
    output_type: null,
    current_game: 31,
    delay_seconds: 0,
    ring: null,
    is_breaking_table: false,
    source: 'manual',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    table_id: 3,
    event_flight_id: 4,
    table_no: 70,
    name: 'Day2-#070',
    type: 'general',
    status: 'setup',
    max_players: 9,
    game_type: 0,
    small_blind: 1200,
    big_blind: 2400,
    ante_type: 1,
    ante_amount: 2400,
    rfid_reader_id: null,
    deck_registered: false,
    output_type: null,
    current_game: null,
    delay_seconds: 0,
    ring: null,
    is_breaking_table: false,
    source: 'manual',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    table_id: 4,
    event_flight_id: 4,
    table_no: 72,
    name: 'Day2-#072',
    type: 'feature',
    status: 'setup',
    max_players: 9,
    game_type: 0,
    small_blind: 1200,
    big_blind: 2400,
    ante_type: 1,
    ante_amount: 2400,
    rfid_reader_id: 2,
    deck_registered: false,
    output_type: 'SDI',
    current_game: null,
    delay_seconds: 30,
    ring: null,
    is_breaking_table: false,
    source: 'manual',
    created_at: NOW,
    updated_at: NOW,
  },
  {
    table_id: 5,
    event_flight_id: 4,
    table_no: 73,
    name: 'Day2-#073',
    type: 'general',
    status: 'empty',
    max_players: 9,
    game_type: 0,
    small_blind: null,
    big_blind: null,
    ante_type: 0,
    ante_amount: 0,
    rfid_reader_id: null,
    deck_registered: false,
    output_type: null,
    current_game: null,
    delay_seconds: 0,
    ring: null,
    is_breaking_table: false,
    source: 'manual',
    created_at: NOW,
    updated_at: NOW,
  },
]

export const mockSeats: TableSeat[] = [
  { seat_id: 1, table_id: 1, seat_no: 1, player_id: 1, wsop_id: 'P-00001', player_name: 'Phil Hellmuth', nationality: 'American', country_code: 'US', chip_count: 142500, profile_image: null, status: 'occupied', player_move_status: null, created_at: NOW, updated_at: NOW },
  { seat_id: 2, table_id: 1, seat_no: 2, player_id: 2, wsop_id: 'P-00002', player_name: 'Daniel Negreanu', nationality: 'Canadian', country_code: 'CA', chip_count: 87200, profile_image: null, status: 'occupied', player_move_status: null, created_at: NOW, updated_at: NOW },
  { seat_id: 3, table_id: 1, seat_no: 3, player_id: 3, wsop_id: 'P-00003', player_name: 'Doyle Brunson', nationality: 'American', country_code: 'US', chip_count: 215000, profile_image: null, status: 'occupied', player_move_status: null, created_at: NOW, updated_at: NOW },
  { seat_id: 4, table_id: 1, seat_no: 4, player_id: 4, wsop_id: 'P-00004', player_name: 'Johnny Chan', nationality: 'American', country_code: 'US', chip_count: 63400, profile_image: null, status: 'occupied', player_move_status: null, created_at: NOW, updated_at: NOW },
  { seat_id: 5, table_id: 1, seat_no: 5, player_id: 5, wsop_id: 'P-00005', player_name: 'Stu Ungar', nationality: 'American', country_code: 'US', chip_count: 330000, profile_image: null, status: 'occupied', player_move_status: null, created_at: NOW, updated_at: NOW },
  { seat_id: 6, table_id: 1, seat_no: 6, player_id: 6, wsop_id: 'P-00006', player_name: 'Erik Seidel', nationality: 'American', country_code: 'US', chip_count: 178000, profile_image: null, status: 'occupied', player_move_status: null, created_at: NOW, updated_at: NOW },
  { seat_id: 7, table_id: 1, seat_no: 7, player_id: 7, wsop_id: 'P-00007', player_name: 'Chris Moneymaker', nationality: 'American', country_code: 'US', chip_count: 94500, profile_image: null, status: 'occupied', player_move_status: null, created_at: NOW, updated_at: NOW },
  { seat_id: 8, table_id: 1, seat_no: 8, player_id: 8, wsop_id: 'P-00008', player_name: 'Vanessa Selbst', nationality: 'American', country_code: 'US', chip_count: 112000, profile_image: null, status: 'occupied', player_move_status: null, created_at: NOW, updated_at: NOW },
  { seat_id: 9, table_id: 1, seat_no: 9, player_id: 9, wsop_id: 'P-00009', player_name: 'Fedor Holz', nationality: 'German', country_code: 'DE', chip_count: 201000, profile_image: null, status: 'occupied', player_move_status: null, created_at: NOW, updated_at: NOW },
]

export const mockPlayers: Player[] = [
  { player_id: 1,  wsop_id: 'P-00001', first_name: 'Phil',      last_name: 'Hellmuth',    nationality: 'American', country_code: 'US', profile_image: null, player_status: 'active', is_demo: false, source: 'manual', synced_at: null, created_at: NOW, updated_at: NOW },
  { player_id: 2,  wsop_id: 'P-00002', first_name: 'Daniel',    last_name: 'Negreanu',    nationality: 'Canadian', country_code: 'CA', profile_image: null, player_status: 'active', is_demo: false, source: 'manual', synced_at: null, created_at: NOW, updated_at: NOW },
  { player_id: 3,  wsop_id: 'P-00003', first_name: 'Doyle',     last_name: 'Brunson',     nationality: 'American', country_code: 'US', profile_image: null, player_status: 'active', is_demo: false, source: 'manual', synced_at: null, created_at: NOW, updated_at: NOW },
  { player_id: 4,  wsop_id: 'P-00004', first_name: 'Johnny',    last_name: 'Chan',        nationality: 'American', country_code: 'US', profile_image: null, player_status: 'active', is_demo: false, source: 'manual', synced_at: null, created_at: NOW, updated_at: NOW },
  { player_id: 5,  wsop_id: 'P-00005', first_name: 'Stu',       last_name: 'Ungar',       nationality: 'American', country_code: 'US', profile_image: null, player_status: 'active', is_demo: false, source: 'manual', synced_at: null, created_at: NOW, updated_at: NOW },
  { player_id: 6,  wsop_id: 'P-00006', first_name: 'Erik',      last_name: 'Seidel',      nationality: 'American', country_code: 'US', profile_image: null, player_status: 'active', is_demo: false, source: 'manual', synced_at: null, created_at: NOW, updated_at: NOW },
  { player_id: 7,  wsop_id: 'P-00007', first_name: 'Chris',     last_name: 'Moneymaker',  nationality: 'American', country_code: 'US', profile_image: null, player_status: 'active', is_demo: false, source: 'manual', synced_at: null, created_at: NOW, updated_at: NOW },
  { player_id: 8,  wsop_id: 'P-00008', first_name: 'Vanessa',   last_name: 'Selbst',      nationality: 'American', country_code: 'US', profile_image: null, player_status: 'active', is_demo: false, source: 'manual', synced_at: null, created_at: NOW, updated_at: NOW },
  { player_id: 9,  wsop_id: 'P-00009', first_name: 'Fedor',     last_name: 'Holz',        nationality: 'German',   country_code: 'DE', profile_image: null, player_status: 'active', is_demo: false, source: 'manual', synced_at: null, created_at: NOW, updated_at: NOW },
  { player_id: 10, wsop_id: 'P-00010', first_name: 'Justin',    last_name: 'Bonomo',      nationality: 'American', country_code: 'US', profile_image: null, player_status: 'active', is_demo: false, source: 'manual', synced_at: null, created_at: NOW, updated_at: NOW },
]

export const mockUser = {
  user: {
    user_id: 1,
    email: 'admin@ebs.local',
    display_name: 'Admin',
    role: 'admin',
    table_ids: [],
  },
  session: {
    last_series_id: 1,
    last_event_id: 1,
    last_flight_id: 4,
    last_table_id: 1,
  },
}

export const mockBlindStructures: BlindStructure[] = [
  { blind_structure_id: 1, name: 'Standard 20min', created_at: NOW, updated_at: NOW },
  { blind_structure_id: 2, name: 'Turbo 12min', created_at: NOW, updated_at: NOW },
  { blind_structure_id: 3, name: 'Deep Stack 30min', created_at: NOW, updated_at: NOW },
]
