/// DriftEvent — chip count reconcile drift record.
///
/// Generated by [ChipCountReconcile] when Engine's auto-computed chip_count
/// diverges from WSOP LIVE webhook truth beyond threshold.
///
/// Spec: docs/2. Development/2.5 Shared/Chip_Count_State.md §3
library;

/// Severity level of a chip count drift.
///
/// NORMAL is intentionally NOT exposed — silent reconciles produce no event.
/// Only MINOR / MAJOR / CRITICAL records are emitted.
enum DriftLevel {
  /// drift threshold breached but ≤ 1000 absolute.
  /// Logged for trend analysis; no operational alert.
  minor,

  /// drift > 1000 OR > 10% of engine_value.
  /// Logged + Slack #ebs-ops alert (handled by BO consumer of drift_event).
  major,

  /// drift > 10000 OR > 10% × 2 of engine_value.
  /// Logged + alert + Engine FSM inspection recommended.
  critical,
}

/// DriftEvent payload — emitted per seat when reconcile detects a drift
/// beyond the silent-reconcile threshold (5% × engine_value with a floor
/// of 1000 abs).
///
/// Race-avoidance: each record carries the hand FSM phase at the moment
/// reconcile ran. If the phase was an active street (preflop/flop/turn/
/// river/showdown/runItMultiple), [auditedDuringActiveHand] is true so
/// operations can review whether the webhook arrived outside the break
/// window.
class DriftEvent {
  /// webhook idempotency key (UUID string).
  final String snapshotId;

  /// EBS table id (cross-stream identifier).
  final int tableId;

  /// Seat number as supplied by the webhook (preserved verbatim for audit).
  final int seatNumber;

  /// Player id (nullable when seat is empty / unknown).
  final int? playerId;

  /// Engine's value at moment of reconcile (pre-swap).
  final int engineValue;

  /// WSOP LIVE webhook value (adopted as truth).
  final int webhookTruth;

  /// |webhookTruth - engineValue|.
  final int driftAmount;

  /// Severity classification (see [DriftLevel]).
  final DriftLevel driftLevel;

  /// WSOP LIVE break id (groups all tables in same break push).
  final int breakId;

  /// Dealer input timestamp (authority moment, from webhook).
  final DateTime recordedAt;

  /// Reconcile execution timestamp (Engine-local clock).
  final DateTime detectedAt;

  /// Hand FSM phase at moment of reconcile. Used for race-avoidance audit.
  final String fsmPhaseAtDetection;

  /// True if reconcile ran while hand FSM was in an active street.
  /// Indicates a race condition — webhook arrived during a hand instead of
  /// during the break. Operations review recommended.
  final bool auditedDuringActiveHand;

  /// Operator-supplied notes (post-hoc). Empty by default.
  final String notes;

  const DriftEvent({
    required this.snapshotId,
    required this.tableId,
    required this.seatNumber,
    required this.playerId,
    required this.engineValue,
    required this.webhookTruth,
    required this.driftAmount,
    required this.driftLevel,
    required this.breakId,
    required this.recordedAt,
    required this.detectedAt,
    required this.fsmPhaseAtDetection,
    this.auditedDuringActiveHand = false,
    this.notes = '',
  });

  /// JSON serialization — matches `chip_count_drift_events` schema
  /// (Chip_Count_State.md §3.2) plus race-avoidance fields.
  Map<String, dynamic> toJson() => {
        'snapshot_id': snapshotId,
        'table_id': tableId,
        'seat_number': seatNumber,
        'player_id': playerId,
        'engine_value': engineValue,
        'webhook_truth': webhookTruth,
        'drift_amount': driftAmount,
        'drift_level': driftLevel.name,
        'break_id': breakId,
        'recorded_at': recordedAt.toUtc().toIso8601String(),
        'detected_at': detectedAt.toUtc().toIso8601String(),
        'fsm_phase_at_detection': fsmPhaseAtDetection,
        'audited_during_active_hand': auditedDuringActiveHand,
        'notes': notes,
      };

  @override
  String toString() =>
      'DriftEvent(table=$tableId seat=$seatNumber engine=$engineValue '
      'truth=$webhookTruth drift=$driftAmount level=${driftLevel.name} '
      'fsm=$fsmPhaseAtDetection'
      '${auditedDuringActiveHand ? ' [RACE]' : ''})';
}
