#!/usr/bin/env python3
"""
Sync team_assignment.yaml → GitHub infrastructure.

Generates / updates and applies branch protection.

Usage:
  python sync_design_to_github.py --config=docs/.../team_assignment.yaml [--dry-run]
"""
import argparse
import json
import subprocess
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write("PyYAML required\n")
    sys.exit(1)

SCRIPT_DIR = Path(__file__).resolve().parent
SKILL_DIR = SCRIPT_DIR.parent


def render_codeowners(config, owner_handle):
    lines = ["# Auto-generated by orchestrator/sync_design_to_github.py", "",
             f"*  {owner_handle}", ""]
    for sid, scfg in config.get('streams', {}).items():
        lines.append(f"# Stream {sid} {scfg.get('name', '')}")
        for phase in scfg.get('phases', {}).values():
            for path in phase.get('scope_owns', []):
                co_path = '/' + path.replace('/**', '/').rstrip('/')
                lines.append(f"{co_path}  {owner_handle}")
        lines.append("")
    meta = config.get('meta_files', {})
    if meta:
        lines.append("# Meta files (orchestrator only)")
        for f in meta.get('files', []):
            lines.append(f"/{f}  {owner_handle}")
        lines.append(f"/.github/  {owner_handle}")
    return "\n".join(lines) + "\n"


def render_branch_protection():
    return {
        "required_pull_request_reviews": {
            "required_approving_review_count": 1,
            "dismiss_stale_reviews": True,
            "require_code_owner_reviews": True
        },
        "required_status_checks": {
            "strict": True,
            "contexts": ["scope_check", "dependency_check", "phase_gate_check"]
        },
        "enforce_admins": False,
        "allow_force_pushes": False,
        "allow_deletions": False,
        "required_linear_history": True
    }


def get_repo_handle():
    try:
        r = subprocess.run(['gh', 'repo', 'view', '--json', 'owner,name'],
                           capture_output=True, text=True, timeout=10)
        if r.returncode == 0:
            d = json.loads(r.stdout)
            return f"{d['owner']['login']}/{d['name']}", f"@{d['owner']['login']}"
    except Exception:
        pass
    return None, None


def apply_branch_protection(repo, dry_run):
    config = render_branch_protection()
    if dry_run:
        print(f"  [DRY] Would PUT branch protection to {repo}/main")
        return
    try:
        r = subprocess.run([
            'gh', 'api', f'repos/{repo}/branches/main/protection',
            '-X', 'PUT', '--input', '-'
        ], input=json.dumps(config), capture_output=True, text=True, timeout=30)
        if r.returncode == 0:
            print(f"  ✓ Branch protection applied to {repo}/main")
        else:
            print(f"  ⚠ Branch protection failed: {r.stderr[:200]}")
    except Exception as e:
        print(f"  ⚠ Branch protection error: {e}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--config', required=True)
    parser.add_argument('--project-root', default='.')
    parser.add_argument('--dry-run', action='store_true')
    parser.add_argument('--apply-bp', action='store_true', help='Apply branch protection')
    args = parser.parse_args()

    config_path = Path(args.config).resolve()
    project_root = Path(args.project_root).resolve()
    config = yaml.safe_load(config_path.read_text(encoding='utf-8'))

    repo, owner = get_repo_handle()
    if not owner:
        owner = "@orchestrator"

    print(f"📂 Project: {project_root}")
    print(f"🐙 Repo:    {repo or '(unknown)'}")
    print(f"👤 Owner:   {owner}\n")

    github = project_root / '.github'
    github.mkdir(exist_ok=True)

    # CODEOWNERS
    codeowners_path = github / 'CODEOWNERS'
    content = render_codeowners(config, owner)
    if not args.dry_run:
        codeowners_path.write_text(content, encoding='utf-8')
    print(f"  ✓ {codeowners_path}")

    # branch-protection.yml (declarative reference)
    bp_path = github / 'branch-protection.yml'
    if not args.dry_run:
        bp_path.write_text(yaml.safe_dump(render_branch_protection(), sort_keys=False),
                           encoding='utf-8')
    print(f"  ✓ {bp_path}")

    # Apply via gh API
    if args.apply_bp and repo:
        print("\n🔒 Applying branch protection:")
        apply_branch_protection(repo, args.dry_run)

    print(f"\n{'[DRY] ' if args.dry_run else ''}✅ Sync complete")


if __name__ == "__main__":
    main()
