#!/usr/bin/env python3
"""confluence_pagename_audit — Audit Confluence page title vs local file stem.

S11 Cycle 11 follow-up to confluence_drift_check.py. The drift checker only
verifies parent ancestry; it does NOT compare page titles. This script does
exactly that: for every mirror-targeted .md file, fetch the live Confluence
title and compare it against the file stem.

Why this matters:
    Cycle 10 linkify originally emitted <ac:link><ri:page ri:content-title="{stem}"/>
    assuming "Confluence page name = file stem". The live state breaks this
    invariant for all 7 Product PRDs (Foundation.md -> "EBS 기초 기획서", etc.).
    Cycle 11 switched to URL-first anchors so the mismatch no longer kills
    cross-links — but the mismatch itself is still informational and may
    require sync (rename Confluence pages OR keep current state).

Usage:
    python tools/confluence_pagename_audit.py              # console report
    python tools/confluence_pagename_audit.py --json       # machine-readable
    python tools/confluence_pagename_audit.py --filter "1. Product/*"
    python tools/confluence_pagename_audit.py --markdown   # appendable matrix

Exit codes:
    0 — all titles match stem (or only excluded mismatches)
    1 — title-vs-stem mismatch detected (informational, NOT a CI failure)
    2 — config / network error

This tool is intentionally read-only. No page rename happens here — that is
a destructive operation requiring user approval; this script only reports.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

if sys.platform == "win32":
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8")

sys.path.insert(0, "C:/claude")
from lib.confluence.md2confluence import api_get, get_config  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent))
from sync_confluence import find_mirror_targets  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent


def fetch_title(cfg: dict, page_id: str) -> str:
    info = api_get(cfg, f"/content/{page_id}", {"expand": "version"})
    return info.get("title", "")


def audit(filter_glob: str | None) -> list[dict]:
    cfg = get_config()
    if not cfg["email"] or not cfg["token"]:
        print("ERROR: ATLASSIAN_EMAIL/TOKEN required", file=sys.stderr)
        sys.exit(2)

    targets = find_mirror_targets(filter_glob)
    rows: list[dict] = []
    for md, page_id, _parent in targets:
        try:
            rel = str(md.relative_to(REPO_ROOT)).replace("\\", "/")
        except ValueError:
            rel = str(md).replace("\\", "/")
        try:
            title = fetch_title(cfg, page_id)
        except Exception as e:
            rows.append({
                "file": rel,
                "stem": md.stem,
                "page_id": page_id,
                "title": "",
                "match": False,
                "error": str(e),
            })
            continue
        rows.append({
            "file": rel,
            "stem": md.stem,
            "page_id": page_id,
            "title": title,
            "match": title == md.stem,
        })
    return rows


def render_console(rows: list[dict]) -> None:
    matches = sum(1 for r in rows if r.get("match"))
    mismatches = [r for r in rows if not r.get("match") and not r.get("error")]
    errors = [r for r in rows if r.get("error")]
    total = len(rows)

    print(f"[pagename audit] {total} target(s) scanned\n")
    print(f"  matches    : {matches}/{total}")
    print(f"  mismatches : {len(mismatches)}")
    print(f"  errors     : {len(errors)}")
    print()

    if mismatches:
        print("Title-vs-stem mismatches:")
        for r in mismatches:
            print(f"  [MISMATCH] {r['file']}")
            print(f"             stem  : {r['stem']}")
            print(f"             title : {r['title']}")
            print(f"             id    : {r['page_id']}")
        print()
    if errors:
        print("API errors (treated as mismatch):")
        for r in errors:
            print(f"  [ERR ] {r['file']} (id={r['page_id']}): {r['error']}")
        print()


def render_markdown(rows: list[dict]) -> str:
    lines = [
        "# Confluence Page-Name Audit",
        "",
        "Auto-generated by `tools/confluence_pagename_audit.py`. Mismatches are",
        "informational — Cycle 11 linkify uses page-id URL anchors, so cross-links",
        "work regardless of title. Rename Confluence pages only with explicit user",
        "approval (bookmarks + search history may break).",
        "",
        "| File | Stem | Confluence Title | Match |",
        "|---|---|---|---|",
    ]
    for r in rows:
        match = "OK" if r.get("match") else ("ERR" if r.get("error") else "MISMATCH")
        title = r.get("title", "") or r.get("error", "")
        lines.append(f"| `{r['file']}` | `{r['stem']}` | {title} | {match} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--filter", help="Glob filter relative to docs/")
    ap.add_argument("--json", action="store_true", help="Emit JSON to stdout")
    ap.add_argument("--markdown", action="store_true", help="Emit markdown table to stdout")
    args = ap.parse_args()

    rows = audit(args.filter)

    if args.json:
        json.dump(rows, sys.stdout, indent=2, ensure_ascii=False)
        sys.stdout.write("\n")
    elif args.markdown:
        sys.stdout.write(render_markdown(rows))
    else:
        render_console(rows)

    mismatch_count = sum(1 for r in rows if not r.get("match"))
    return 1 if mismatch_count else 0


if __name__ == "__main__":
    sys.exit(main())
