#!/usr/bin/env python3
"""team_v5_merge.py — v5.0 Phase 2 구현 (PR 생성 + auto-merge 라벨).

v5.0 Workflow:
  1. 현재 브랜치 (work/team{N}/<slug>) 확인
  2. origin/main 에 rebase
  3. force-push work 브랜치
  4. gh pr create --fill --base main
  5. auto-merge 라벨 부착 → `.github/workflows/pr-auto-merge.yml` 트리거

Free-tier 호환:
  - `gh pr merge --auto` (private free 플랜 지원 안 함) 대신 라벨 기반 트리거
  - Merge Queue (Team plan) 대신 workflow concurrency group

Usage:
  # 자동 감지 (현재 branch, 현재 cwd 기준 팀)
  python tools/team_v5_merge.py

  # 수동 지정
  python tools/team_v5_merge.py --branch work/team2/settings-kv
  python tools/team_v5_merge.py --dry-run    # PR body 미리 보기

Exit:
  0 — PR 생성 + auto-merge 라벨 부착 성공
  1 — rebase conflict
  2 — push / PR create 실패
  3 — 환경 오류 (gh 미설치, sibling worktree 아님 등)
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
AUTO_MERGE_LABEL = "auto-merge"


def _run(cmd: list[str]) -> tuple[int, str, str]:
    r = subprocess.run(cmd, cwd=REPO, capture_output=True, text=True, timeout=60)
    return r.returncode, r.stdout, r.stderr


def _check_env() -> tuple[bool, str]:
    """환경 사전 체크 — gh CLI, gh auth, sibling worktree."""
    rc, _, _ = _run(["gh", "--version"])
    if rc != 0:
        return False, "gh CLI 미설치. https://cli.github.com/ 참조"

    rc, _, err = _run(["gh", "auth", "status"])
    if rc != 0:
        return False, f"gh 인증 필요. `gh auth login` 실행. ({err[:100]})"

    # sibling worktree 체크 (repo path 가 ebs-team{N}-* 패턴인가)
    repo_name = REPO.name.lower()
    is_conductor = repo_name == "ebs"
    is_team_sibling = bool(re.match(r"ebs-team[1-4]-", repo_name))

    if not (is_conductor or is_team_sibling):
        return False, f"예상치 못한 repo 경로: {REPO}. ebs/ 또는 ebs-team{{N}}-<slug>/ 필요"

    return True, ""


def _current_branch() -> str:
    rc, out, _ = _run(["git", "branch", "--show-current"])
    return out.strip() if rc == 0 else ""


def _team_from_branch(branch: str) -> str:
    """work/team2/foo → team2, otherwise conductor."""
    m = re.match(r"work/(team[1-4])/", branch)
    return m.group(1) if m else "conductor"


def _pr_body(branch: str, team: str) -> str:
    """PR description 자동 생성."""
    rc, log, _ = _run(["git", "log", "origin/main..HEAD", "--oneline"])
    commits = log.strip() or "(no commits yet)"

    rc, diffstat, _ = _run(["git", "diff", "origin/main...HEAD", "--stat"])

    return f"""## v5.0 Auto-PR ({team})

**Branch**: `{branch}`
**Team**: {team}
**Auto-merge**: enabled via `auto-merge` label + `pr-auto-merge.yml`

### Commits
```
{commits}
```

### Diffstat
```
{diffstat[:2000]}
```

### Review
- CODEOWNERS 자동 배정 (`{team}` 소유 경로 기준)
- CI pass + concurrency slot 획득 시 자동 squash-merge

_Generated by `tools/team_v5_merge.py`. 수동 수정 환영._
"""


def prepare_branch(branch: str, dry_run: bool) -> dict:
    """work 브랜치를 origin/main 에 rebase + force-push."""
    log = {"branch": branch, "steps": [], "error": None}

    # fetch
    rc, _, err = _run(["git", "fetch", "origin"])
    log["steps"].append({"step": "fetch", "rc": rc})
    if rc != 0:
        log["error"] = f"fetch failed: {err[:150]}"
        return log

    # checkout target branch
    cur = _current_branch()
    if cur != branch:
        rc, _, err = _run(["git", "checkout", branch])
        log["steps"].append({"step": "checkout", "rc": rc})
        if rc != 0:
            log["error"] = f"checkout {branch} failed: {err[:150]}"
            return log

    # rebase on origin/main
    if dry_run:
        log["steps"].append({"step": "rebase (skipped, dry-run)", "rc": 0})
    else:
        rc, _, err = _run(["git", "rebase", "origin/main"])
        log["steps"].append({"step": "rebase origin/main", "rc": rc})
        if rc != 0:
            _run(["git", "rebase", "--abort"])
            log["error"] = "rebase conflict"
            return log

        # push (force-with-lease)
        rc, _, err = _run(["git", "push", "--force-with-lease", "origin", branch])
        log["steps"].append({"step": "push work", "rc": rc})
        if rc != 0:
            log["error"] = f"push failed: {err[:150]}"
            return log

    return log


def create_pr(branch: str, team: str, dry_run: bool) -> dict:
    """gh pr create + auto-merge 라벨 부착."""
    result = {"pr_url": None, "steps": [], "error": None}

    body = _pr_body(branch, team)
    title = _infer_title(branch)

    if dry_run:
        result["dry_run_preview"] = {"title": title, "body": body[:500]}
        return result

    # 기존 PR 재사용
    rc, existing, _ = _run([
        "gh", "pr", "view", branch, "--json", "url,state", "-q", ".url"
    ])
    if rc == 0 and existing.strip():
        result["pr_url"] = existing.strip()
        result["steps"].append({"step": "pr exists (reused)", "rc": 0})
    else:
        # 신규 PR
        rc, out, err = _run([
            "gh", "pr", "create",
            "--title", title,
            "--body", body,
            "--base", "main",
            "--head", branch,
        ])
        result["steps"].append({"step": "pr create", "rc": rc})
        if rc != 0:
            result["error"] = f"gh pr create failed: {(err or out)[:200]}"
            return result
        result["pr_url"] = out.strip().splitlines()[-1] if out.strip() else ""

    # auto-merge 라벨 부착
    rc, _, err = _run([
        "gh", "pr", "edit", branch,
        "--add-label", AUTO_MERGE_LABEL,
    ])
    result["steps"].append({"step": "add auto-merge label", "rc": rc})
    if rc != 0:
        # 라벨이 없으면 생성 후 재시도
        _run([
            "gh", "label", "create", AUTO_MERGE_LABEL,
            "--color", "0E8A16",
            "--description", "v5.0 PR auto-merge workflow trigger",
        ])
        rc, _, err = _run([
            "gh", "pr", "edit", branch,
            "--add-label", AUTO_MERGE_LABEL,
        ])
        result["steps"].append({"step": "add label retry", "rc": rc})
        if rc != 0:
            result["error"] = f"label attach failed: {err[:150]}"
            return result

    return result


def _infer_title(branch: str) -> str:
    """work/team2/settings-kv → 'team2: settings-kv (auto)' 형식."""
    m = re.match(r"work/(team[1-4])/(.+)", branch)
    if m:
        return f"{m.group(1)}: {m.group(2)} (v5.0 auto)"
    return f"{branch} (v5.0 auto)"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--branch", default="",
                    help="대상 work 브랜치 (기본: 현재 체크아웃된 브랜치)")
    ap.add_argument("--dry-run", action="store_true",
                    help="PR body 미리 보기 + rebase/push/create 안 함")
    args = ap.parse_args()

    # 환경 체크
    ok, msg = _check_env()
    if not ok and not args.dry_run:
        print(f"[error] {msg}", file=sys.stderr)
        return 3

    branch = args.branch or _current_branch()
    if not branch:
        print("[error] 현재 브랜치 감지 실패", file=sys.stderr)
        return 3

    if branch == "main":
        print("[error] main 브랜치에서 실행 불가. work/team{N}/<slug> 로 전환 후 재시도", file=sys.stderr)
        return 3

    team = _team_from_branch(branch)

    print(f"=== v5.0 Phase 2 (PR 생성) ===")
    print(f"  branch: {branch}")
    print(f"  team:   {team}")
    print(f"  dry-run: {args.dry_run}\n")

    # Phase 2.1: rebase + push
    prep = prepare_branch(branch, args.dry_run)
    print("--- prepare ---")
    print(json.dumps(prep, indent=2, ensure_ascii=False))
    if prep.get("error"):
        if "rebase conflict" in prep["error"]:
            return 1
        return 2

    # Phase 2.2: PR create + label
    pr = create_pr(branch, team, args.dry_run)
    print("\n--- PR ---")
    print(json.dumps(pr, indent=2, ensure_ascii=False))
    if pr.get("error"):
        return 2

    if args.dry_run:
        print("\n✓ dry-run 완료. 실제 실행은 --dry-run 빼고 재호출")
        return 0

    print(f"\n✅ v5.0 PR 준비 완료: {pr['pr_url']}")
    print(f"   Phase 3 (auto-merge) 는 `.github/workflows/pr-auto-merge.yml` 이 백그라운드 처리")
    print(f"   상태 확인: gh pr view {branch}")

    # v5.1: Active_Work claim 자동 release (best-effort)
    _release_v5_1_claim(branch, team, pr.get("pr_url"))
    return 0


def _release_v5_1_claim(branch: str, team: str, pr_url: str | None) -> None:
    """v5.1 Pre-Work Contract: 이 branch 와 연결된 claim 자동 release.

    Active_Work.md 에서 team 이 편집한 scope 를 역추적. PR URL 이 일치하거나
    해당 team 의 최신 claim 을 해제. 실패 시 침묵 (coordination 도구이므로
    PR 동작에 영향 주지 않음).
    """
    cli = REPO / "tools" / "active_work_claim.py"
    if not cli.exists():
        return
    try:
        import json as _json
        rc, out, _ = _run([
            sys.executable, str(cli), "list", "--team", team, "--json",
        ])
        if rc != 0 or not out.strip():
            return
        data = _json.loads(out)
        active = data.get("active", [])
        if not active:
            return
        # PR URL 매칭 우선. 없으면 가장 오래된 active claim 을 대상으로
        target = next((c for c in active if c.get("pr") == pr_url), None)
        if target is None and active:
            target = sorted(active, key=lambda x: x.get("started", ""))[0]
        if target is None:
            return
        cid = target.get("id")
        # PR URL 갱신 후 release
        if pr_url and target.get("pr") != pr_url:
            _run([sys.executable, str(cli), "update", "--id", str(cid), "--pr", pr_url])
        _run([sys.executable, str(cli), "release", "--id", str(cid)])
        print(f"   ✅ v5.1 Active_Work claim #{cid} released")
    except Exception as e:
        # 침묵 (coordination 도구는 PR 에 영향 X)
        print(f"   [warn] Active_Work release 실패 (수동 release 필요): {str(e)[:100]}")


if __name__ == "__main__":
    sys.exit(main())
